server:
  port: 8081
spring:
  application:
    name: novel-service
  datasource:
    url: jdbc:oracle:thin:@192.168.214.129:1521/pdborcl  # 替换为你的数据库连接信息
    username: novel                      # 替换为你的数据库用户名
    password: 123456                       # 替换为你的数据库密码
    driver-class-name: oracle.jdbc.OracleDriver
logging:
  level:
    com.swxy: debug
  pattern:
    dateformat: HH:mm:ss
knife4j:
  enable: true
  openapi:
    title: 小说接口文档
    description: "小说接口文档"
    email: zhanghuyi@itcast.cn
    concat: wfh
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.swxy.novel.controller
mybatis-plus:
  type-aliases-package: com.swxy.novel.entity
  configuration:
    #mybatis-plus发送null给oracle是会报错，所以增加此参数
    jdbc-type-for-null: 'null'
  mapper-locations: "classpath*:/mapper/**/*.xml"


