server:
  port: 8081
spring:
  application:
    name: novel-service
  profiles:
    active: local
  datasource:
    url: jdbc:oracle:thin:@${hzg.db.host}:1521:${hzg.db.servicename}  # 替换为你的数据库连接信息
    username: ${hzg.db.username}                      # 替换为你的数据库用户名
    password: ${hzg.db.pwd}                       # 替换为你的数据库密码
    driver-class-name: oracle.jdbc.OracleDriver
logging:
  level:
    com.swxy: debug
  pattern:
    dateformat: HH:mm:ss
knife4j:
  enable: true
  openapi:
    title: 小说接口文档
    description: "小说接口文档"
    email: wu2740461899@163.com
    concat: wfh
    url: https://swxy.csuft.edu.cn/
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.swxy.novel.controller
mybatis-plus:
  type-aliases-package: com.swxy.novel.domain
  configuration:
    #mybatis-plus发送null给oracle是会报错，所以增加此参数
    jdbc-type-for-null: 'null'
  mapper-locations: "classpath*:/mapper/**/*.xml"


