server:
  port: 8083
spring:
  cloud:
    nacos:
      config:
        server-addr: 192.168.214.129:8848
  application:
    name: chapter-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${hzg.db.host}:3306/${hzg.db.servicename}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${hzg.db.username}
    password: ${hzg.db.pwd}
  servlet:
    multipart:
      max-file-size: 30MB
logging:
  level:
    com.swxy: debug
  pattern:
    dateformat: HH:mm:ss
knife4j:
  enable: true
  openapi:
    title: 章节接口文档
    description: "章节接口文档"
    email: wu2740461899@163.com
    concat: wfh
    url: https://swxy.csuft.edu.cn/
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.swxy.chapter.controller
mybatis-plus:
  type-aliases-package: com.swxy.chapter.domain
  mapper-locations: "classpath*:/mapper/**/*.xml"
feign:
  okhttp:
    enabled: true # 开启OKHttp功能

