CREATE TABLE novels (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    author VARCHAR2(100),
    status VARCHAR2(50),
    update_time VARCHAR2(100),
    introduction CLOB
) TABLESPACE novel_space;
ALTER TABLE novels
ADD image_path VARCHAR2(255);

-- 5. 为表添加注释
COMMENT ON TABLE novels IS '存储小说信息的表';
-- 6. 为列添加注释
COMMENT ON COLUMN novels.id IS '主键，自增的小说ID';
COMMENT ON COLUMN novels.title IS '小说标题';
COMMENT ON COLUMN novels.author IS '作者名称';
COMMENT ON COLUMN novels.status IS '小说状态';
COMMENT ON COLUMN novels.update_time IS '最后更新时间';
COMMENT ON COLUMN novels.introduction IS '小说简介';
COMMENT ON COLUMN novels.image_path IS '小说封面图片路径';

CREATE TABLE chapters (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    novel_id NUMBER NOT NULL, -- 外键，指向小说表
    title VARCHAR2(255) NOT NULL, -- 章节标题
    content CLOB NOT NULL, -- 章节内容
    update_time DATE DEFAULT SYSDATE, -- 更新时间
    FOREIGN KEY (novel_id) REFERENCES novels(id) -- 外键约束
) TABLESPACE novel_space;

ALTER TABLE chapters
ADD chapter_id NUMBER;

COMMENT ON TABLE chapters IS '存储小说章节信息的表';
COMMENT ON COLUMN chapters.id IS '主键，自增的章节ID';
COMMENT ON COLUMN chapters.novel_id IS '指向所属小说的ID';
COMMENT ON COLUMN chapters.title IS '章节标题';
COMMENT ON COLUMN chapters.content IS '章节内容';
COMMENT ON COLUMN chapters.update_time IS '章节最后更新时间';
COMMENT ON COLUMN chapters.chapter_id IS '章节id';

